### ISSUE TITLE
Application oversized

### ISSUE THREAD

**Issue by BDenBleyker** [NeblioTeam/neblio#29]
Upon opening the application, one can only see the top left corner of the non-re-sizable window.

Operating on Windows 10.

**Comment by NeblioTeam** [comment]
A few other users have reported this in rare cases on windows 10 with very high or very low DPI monitors. This is a bug in QT, the framework we use for the GUI. All cases that I know of have been able to fix the issue by right-clicking on the .exe file, clicking properties, clicking compatibility, and then playing with the DPI settings until it works. 

Since I cannot reproduce this myself, if you cannot get it working I'd suggest joining either our slack or telegram and maybe another user that had the issue can describe exactly which setting they changed. https://nebl.io/chat

**Comment by ithound** [comment]
This solves the problem and below are the steps:

1. Right click the exe and select PROPERTIES
2. Click on COMPATBILITY TAB
3. Check the box "Override high DPI scaling behaviour Scaling perormed by:"
4. Select "System" from the dropdown list below
5. Click APPLY then OK
