### ISSUE TITLE
Missing Nebliod beginners guide

### ISSUE THREAD

**Issue by jphellemons** [NeblioTeam/neblio#330]
Hi, I've just pulled the docker image from docker hub for the raspberry pi. I have checked out `nebliod getinfo` and also the `nebliod getwalletinfo` 
I haven't created a wallet or specified a passphrase or anything. So how do I do that or is it created by default? How do I find the wallet address from the cli? Because listaccounts says:

> error: {"code":-1,"message":"Accounting API is deprecated and will be removed in future.\nIt can easily result in negative or odd balances if misused or misunderstood, which has happened in the field.\nIf you still want to enable it, add to your config file enableaccounts=1 and it is HIGHLY recommended that staking is DISABLED with staking=0\n"}

So I'd like to see my walletaddress and enable staking (after I have transfered to it) Shouldn't be that hard. So if someone can help me with that or point me to the correct documentation. That would be nice :)

**Comment by NeblioTeam** [comment]
Documentation is pretty sparse for the docker images as they are usually used by users with both Neblio and Docker experience. We would be extremely interested in a writeup of your experience and how you would document running the docker container as a new user. We would add this to our knowledge base on the Neblio site and give you credit if you wanted to contribute back to the project by doing a write up. But generally the process is the same as running nebliod without docker.

The reason you are seeing the error message about the Accounting API is because, as the error says, that API is deprecated. What you should be using instead is `listreceivedbyaddress 0 true` to show addresses in your wallet that have 0 balance. `help listreceivedbyaddress` will show the parameters for this RPC command. Note that these commands are generally the same as Bitcoin Core and other similar wallets. Once you have sent NEBL to any of these addresses, simply `listreceivedbyaddress` will show you the addresses in your wallet that have a balance. 

The RPC username and password are set by the docker container on first run. You can view these in the `neblio.conf` file created in the data directory if you like, but once created the user generally does not need to change them. 

Staking will begin automatically, once your wallet has NEBL in it that have matured for 24 hours. You can use the `getstakinginfo` command to view information regarding staking. 

Let us know if you have any further questions, we'd be happy to help.

**Comment by jphellemons** [comment]
Thank you for the reply! I will capture my journey in a blogpost! The nebl has matured. This is the output of the `getstakinginfo` and I was wondering when the first change in the `getbalance` will occur (estimate)
>{
    "enabled" : true,
    "staking" : true,
    "staking-criteria" : {
        "mature-coins" : true,
        "wallet-unlocked" : true,
        "online" : true,
        "synced" : true
    },
    "errors" : "",
    "stakableoutputs" : 1,
    "currentblocksize" : 1000,
    "currentblocktx" : 0,
    "pooledtx" : 0,
    "difficulty" : 0.00812745,
    "search-interval" : 0,
    "weight" : 10,
    "netstakeweight" : 1182721,
    "expectedtime" : 3548163
}

**Comment by NeblioTeam** [comment]
The estimate you are looking for is `"expectedtime" : 3548163` which shows a (very) rough estimate in seconds of the amount of time until your next staking reward. This number is a simple calculation based on `"weight" : 10,` which is the weight your NEBL have gained since maturity (this will increase at approximately 1 per day, per NEBL staking) and `"netstakeweight" : 1182721,` which is the combined weight of all other stakers on the network. So, as your weight increases, expectedtime will, generally, decrease.

https://medium.com/neblio-blog/staking-explained-8c8d67f289c0 has some additional info on these parameters and how staking works on Neblio. 

Let us know if you have any further questions, we'd be happy to help.

**Comment by jphellemons** [comment]
Thanks again for the help! I have written my steps on a blog post which can be found here https://jphellemons.nl/post/stake-neblio-on-your-pi

**Comment by jphellemons** [comment]
Seems that I made an error. as I have used `docker run --rm` so after a reboot it was gone. I did however make a copy of the wallet.dat 
After the reboot I did run it with `-d --restart=always`
when I copied it back it does show balance `0` but when I check the address on https://explorer.nebl.io/ it does show the correct balance. Did I just lost my Nebl?

**Comment by NeblioTeam** [comment]
Assuming you ran the container with `-v $HOME/neblio-data:/root/.neblio` then all of the files specific to your installation, the txlmdb blockchain database, the wallet.dat, the debug.log etc will be stored on the host computer at `$HOME/neblio-data`

So unless you deleted any of these files, they should get mounted and used by the docker container every time it is run. If you aren't seeing the balance you expect, you might need a rescan. Launching the daemon with `-rescan=1` will do a rescan on startup.

**Comment by jphellemons** [comment]
I did indeed use the -v so I still have the wallet and config etc. Could I kill the daemon and restart with `-rescan=1` in a bash terminal? `docker exec -it nebliod bash`

**Comment by NeblioTeam** [comment]
That's one option. You can add `rescan=1` to the `neblio.conf` file in the data directory. Which might be easier.

**Comment by jphellemons** [comment]
> That's one option. You can add `rescan=1` to the `neblio.conf` file in the data directory. Which might be easier.

Thanks, did that. stopped the container and started it again. It's somehow still at mature coins false and sync false (and probably therefor balance 0) how can I check if it's syncing in the background?

**Comment by NeblioTeam** [comment]
The best way to check the current status is tailing debug.log

`tail -f $HOME/neblio-data/debug.log` on the host computer.

**Comment by jphellemons** [comment]
Thanks, but all I get are entries like `02/23/21 18:24:00 Selected network/chain type: main`

**Comment by jphellemons** [comment]
I have used scp to transfer the wallet.dat to my desktop and imported it,. Everything is fine. So the wallet.dat is ok. It's just like the nebliod does seem to ignore the addition of the rescan=1 in the neblio.conf I have looked for some docs to switch the logging detail level for the debug.log but failed to find documentation about that. I would really like to get my docker container on the raspberry pi back in sync because that node can run 24/7. My desktop cannot.

**Comment by NeblioTeam** [comment]
Good to know that the wallet.dat is fine. But as you say, something is still off. 

Our support team will be the fastest way to resolve this, via email. Please open a ticket by contacting support at https://nebl.io/contact-us/ and referencing this issue. Also include the command you are using to run the container.
