### ISSUE TITLE
Cannot sync wallet Mac

### ISSUE THREAD

**Issue by Evanneve7** [NeblioTeam/neblio#37]
I do not know why my wallet isn't syncing.. Any help would be great!

**Comment by NeblioTeam** [comment]
Something on your mac or network is blocking connection to port 6325, the port that Neblio uses to connect to all the other nodes.

Email the file ~/Library/Application Support/neblio/debug.log to info@nebl.io and I will gladly take a look, but I expect I will just see a lot of failed connections, and unfortunately it is impossible for be to debug your firewall and networking setup remotely.

**Comment by NeblioTeam** [comment]
Note that if your wallet did not sync last night, our DNSSeeder was overloaded due to all the new wallets joining the network. We've upgraded that infrastructure. Try closing and re-opening the wallet so that it can fetch a list of nodes to connect to via the upgraded DNSSeeder. Sorry for the inconvenience.
