### ISSUE TITLE
List of working nodes for mac?

### ISSUE THREAD

**Issue by Evanneve7** [NeblioTeam/neblio#39]
Wallet is not syncing due to lack of nodes. I need to add some nodes manually but cannot find any working ones.

**Comment by NeblioTeam** [comment]
Hello,

There is no need for nodes to be added to any config file for Neblio. If you are having trouble connecting to the Neblio network, there is something on your Mac blocking the connection. Since you are on a Mac, do you have any firewall installed, like Little Snitch? Lots of Mac users that used a 3rd party firewall had to to configure it to allow the Neblio wallet access.
