### ISSUE TITLE
Make Change Addresses Optional and Off By Default in neblio-qt

### ISSUE THREAD

**Issue by brycly** [NeblioTeam/neblio#67]
Feature is inconvenient for purpose of Neblio, results in either needing to regroup your coins or to make a new backup file with every transaction. 

Ideally change should be sent back to group that the transaction was made from if possible to simplify the staking process.

**Comment by NeblioTeam** [comment]
I've considered in the past turning on the coin control option by default and also adding an option to automatically include the sending address as the "Custom Change Address" that was also on by default.

This would only affect neblio-qt and not nebliod

I think Sam can take this one when he has some free time.

**Comment by TheQuantumPhysicist** [comment]
@brycly 
In fact, reusing addresses is considered bad practice due to privacy related reasons. Please look here:

https://wiki.bitcoin.com/w/Address_reuse

And hence it should not be made to be the default behavior. We can add this, but:

1. It shouldn't be the default behavior,
2. It should be made with a big, fat warning.

**Comment by TheQuantumPhysicist** [comment]
I just noticed that you talked about backup. Please notice that the wallet generates many new addresses (like a hundred), and just reveals these to you when you generate new addresses. All these go to your backups. Please refer to this:

https://bitcoin.stackexchange.com/questions/13277/how-frequently-should-one-update-wallet-backup

**Comment by NeblioTeam** [comment]
The problem is that I get 10-12 support requests a day relating to change addresses, the helpful community in Slack likely gets more. Users wondering why their address balance on the block explorer is less than their wallet balance, why the transaction on the block explorer shows the 'change' going to an address they've never seen, etc. Despite change addresses being the default in bitcoin core and other similar projects for years now, many users are not familiar with them.

We either need to educate users better, or turn off change addresses by default for noobs, but have it easily turned back on via a simple checkbox on the Send Tokens tab for users that want the privacy. The android wallet has this option, for example.

I agree that address re-use can be bad, especially for bitcoin where it is used as a currency. However NEBL is is currently not used like BTC and change addresses are really confusing many users and we need to find a solution.

**Comment by innnzzz6** [comment]
http://explorer.nebl.io/tx/6c50e6be956a7fba4734a09c484c15440c1c31d51367ddef2b3884dfc0b89c7f

I have withdrawal on 16FEB now I don’t have incoming deposit .. my neblio Cryptopia address :NMMGp5xJRreprWtSV1GuFr4bC8zorD8QbY sent 111.93637442 nebl to my neblio qt but my coin move to the address :NemT2vxEaHBZ6ct3qfGzGHjDP2uWJbnWUL  

Please check it for me ..thanks support 

I need return my coin to my address

**Comment by innnzzz6** [comment]
innnzzz6@gmail.com

Thanks support

**Comment by NeblioTeam** [comment]
We are not implementing this.
