### ISSUE TITLE
St13runtime_error on MAC for Neblio wallet

### ISSUE THREAD

**Issue by Sideshow55555** [NeblioTeam/neblio#92]
![screen shot 2018-03-10 at 22 40 11](https://user-images.githubusercontent.com/35368081/37246560-09159174-24b4-11e8-9a3b-ffafa4d91716.png)

Is their anyway as to rectify this wallet as I have made the cardinal error of not completing a .dat backup file and would like to recover my wallet as it is still on my mac.

Any help would be greatly appreciated.

Kind regards

**Comment by NeblioTeam** [comment]
Yes the database is simply corrupt, normally this happens due to a system crash. Deleting it and resyncing will solve the issue.

Close Neblio
Open Finder
Press CMD+Shift+g
Paste in: ~/Library/Application Support/neblio
Delete everything in this folder **EXCEPT WALLET.dat** <- you will lose all your NEBL if you delete wallet.dat
Restart Neblio and let it re-sync

Then make a backup ;)

**Comment by Sideshow55555** [comment]
Thank you,

It has been sorted, I appreciate you quick response.
